{{- $secretName := printf "%s-qalita-secret" .Release.Name -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secretName }}"
data:
  adminPassword: {{ default (randAlphaNum 25 | b64enc) .Values.backend.adminPassword | b64enc }}
  secretKey: {{ default (randAlphaNum 512 | b64enc) .Values.backend.secretKey | b64enc }}
  licenseKey: {{ if and $existingSecret (not .Values.licenseKey) }}{{ index $existingSecret.data "licenseKey" }}{{ else }}{{ default "unlicenced" .Values.licenseKey | b64enc }}{{ end }}
